version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: "your_db_host"
      DB_USER: "your_db_user"
      DB_PASSWORD: "your_db_password"
      DB_NAME: "your_db_name"
      DB_PORT: "5433" 
